# Generated by Django 5.2.4 on 2025-08-06 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecipientModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=12)),
                ('telegram_username', models.CharField(max_length=50)),
            ],
        ),
    ]
