# Generated by Django 5.2.4 on 2025-08-07 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipientmodel',
            old_name='telegram_username',
            new_name='telegram_chat_id',
        ),
    ]
